version: '3'

services:
  app:
    build: docker/php/.
    image: app
    container_name: app
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /var/www
    volumes:
      - ./:/var/www

  web:
    image: nginx:alpine
    container_name: web
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d

  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

  composer:
    build: docker/composer/.
    container_name: composer
    working_dir: /var/www
    volumes:
      - ./:/var/www

volumes:
  db_data:
